//Global Location Number (GLN) Registry API
//Copyright (C) 2018  University Hospitals Plymouth NHS Trust
//
//You should have received a copy of the GNU Affero General Public License
//along with this program.  If not, see <http://www.gnu.org/licenses/>. 
// 
// See LICENSE in the project root for license information.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gln_registry_aspNet.DbDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gln
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gln()
        {
            this.Extensions = new HashSet<Extensions>();
        }
    
        public int Id { get; set; }
        public string FriendlyDescriptionPurpose { get; set; }
        public bool Active { get; set; }
        public string OwnGln { get; set; }
        public string ParentGln { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool UseParentAddress { get; set; }
        public Nullable<bool> Verified { get; set; }
        public bool FunctionalType { get; set; }
        public bool LegalType { get; set; }
        public bool DigitalType { get; set; }
        public bool PhysicalType { get; set; }
        public bool Public { get; set; }
        public bool Assigned { get; set; }
        public int AddressId { get; set; }
        public int ContactId { get; set; }
        public string SuspensionReason { get; set; }
        public int Version { get; set; }
        public int NumberOfChildren { get; set; }
        public bool TrustActive { get; set; }
        public string SuspendedBy { get; set; }
        public bool Primary { get; set; }
        public string ParentDescriptionPurpose { get; set; }
        public System.DateTime SuspensionDate { get; set; }
        public string TruthDescriptionPurpose { get; set; }
        public bool AlternativeSystemIsTruth { get; set; }
        public string AlternativeSystemPK { get; set; }
        public string AlternativeSystemOfTruthName { get; set; }
        public string Department { get; set; }
        public string Function { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> TierLevel { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Extensions> Extensions { get; set; }
        public virtual PrimaryContacts PrimaryContact { get; set; }
    }
}
