//Global Location Number (GLN) Registry API
//Copyright (C) 2018  University Hospitals Plymouth NHS Trust
//
//You should have received a copy of the GNU Affero General Public License
//along with this program.  If not, see <http://www.gnu.org/licenses/>. 
// 
// See LICENSE in the project root for license information.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gln_registry_aspNet.DbDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlnAssociation
    {
        public int Id { get; set; }
        public int GlnId1 { get; set; }
        public int GlnId2 { get; set; }
    }
}
